// ! Backend say it will be same forever, but i know it will change in the future.
// ! order is very important for debugging

export enum PagesIdSettings {
  settings = 24,

  settingsdocumentcategories = 393,
  settingsdocumentcategoriesdelete = 1923,
  settingsdocumentcategoriesedit = 1922,
  settingsdocumentcategoriesadd = 1921,

  settingsfacilities = 391,
  settingsfacilitiesdelete = 1917,
  settingsfacilitiesedit = 1916,
  settingsfacilitiesadd = 1915,

  settingsameinities = 390,
  settingsameinitiesdelete = 1914,
  settingsameinitiesedit = 1913,
  settingsameinitiesadd = 1912,

  settingsxml = 389,
  settingsxmldelete = 1911,
  settingsxmladd = 1908,
  settingsxmlblock = 1910,
  settingsxmledit = 1909,

  settingswebportal = 388,
  settingswebportaldelete = 1907,
  settingswebportalxml = 1906,
  settingswebportaledit = 1906,
  settingswebportaladd = 1904,

  settingstax = 395,
  settingstaxadd = 1927,
  settingstaxdelete = 1929,
  settingstaxedit = 1928,

  settingscity = 490,
  settingscitymanage = 490,
  settingscitymanageadd = 2714,
  settingscitymanageedit = 2715,
  settingscitymanagedelete = 2716,
  settingscitydeleted = 0,
  settingscitydeletedrestore = 0,

  settingscategory = 493,
  settingscategoryadd = 2723,
  settingscategoryedit = 2724,
  settingscategorydelete = 2725,

  settingscompanytype = 495,
  settingscompanytypeadd = 2729,
  settingscompanytypeview = 2730,
  settingscompanytypeedit = 2731,
  settingscompanytypeedelete = 2732,

  settingsbanks = 496,
  settingsbanksmanage = 0,
  settingsbanksmanageadd = 2733,
  settingsbanksmanageedit = 2734,
  settingsbanksmanagedelete = 2735,
  settingsbanksmanagesubcategorymanage = 2736,
  settingsbanksmanagesubcategorymanageadd = 2737,
  settingsbanksmanagesubcategorymanageedit = 2738,
  settingsbanksmanagesubcategorymanagedelete = 2739,
  settingsbanksmanagesubcategorydeleted = 0,
  settingsbanksmanagesubcategorydeletedrestore = 0,
  settingsbanksdeleted = 0,
  settingsbanksdeletedrestore = 0,

  settingscompanycategory = 501,
  settingscompanycategorymanage = 501,
  settingscompanycategorymanageadd = 2756,
  settingscompanycategorymanageview = 2757,
  settingscompanycategorymanageedit = 2758,
  settingscompanycategorymanageedelete = 2759,
  settingscompanycategorydeleted = 0,
  settingscompanycategorydeletedrestore = 0,

  settingscompanyactivities = 511,
  settingscompanyactivitiesmanage = 511,
  settingscompanyactivitiesmanageadd = 2788,
  settingscompanyactivitiesmanageview = 2789,
  settingscompanyactivitiesmanageedit = 2790,
  settingscompanyactivitiesmanageedelete = 2791,
  settingscompanyactivitiesdeleted = 0,
  settingscompanyactivitiesdeletedrestore = 0,

  settingsaqaryguides = 516,
  settingsaqaryguidesmanage = 0,
  settingsaqaryguidesmanageadd = 2805,
  settingsaqaryguidesmanageedit = 2806,
  settingsaqaryguidesmanagedelete = 2807,
  settingsaqaryguidesdeleted = 0,
  settingsaqaryguidesdeletedrestore = 0,

  settingsbannercost = 548,
  settingsbannercostadd = 3175,
  settingsbannercostmanage = 3173,
  settingsbannercostmanageedit = 3176,
  settingsbannercostmanagedelete = 3177,
  settingsbannercostmanageadd = 3175,
  settingsbannercostdeleted = 3174,
  settingsbannercostdeletedrestore = 3178,

  settingsbannerplanpackage = 549,
  settingsbannerplanpackageedit = 3170,
  settingsbannerplanpackageadd = 3166,
  settingsbannerplanpackagedeleted = 3168,
  settingsbannerplanpackagedeletedrestore = 0,
  settingsbannerplanpackagemanage = 3167,
  settingsbannerplanpackagemanageedit = 3170,
  settingsbannerplanpackagemanagedelete = 3172,

  settingsplatformcredientials = 553,
  settingsplatformcredientialsadd = 3108,
  settingsplatformcredientialsmanage = 3109,
  settingsplatformcredientialsmanageedit = 3111,
  settingsplatformcredientialsmanagedelete = 3112,
  settingsplatformcredientialsdeleted = 3110,
  settingsplatformcredientialsdeletedrestore = 3113,

  settingscommunity = 491,
  settingscommunitymanage = 491,
  settingscommunitymanageadd = 2717,
  settingscommunitymanageedit = 2718,
  settingscommunitymanagedelete = 2719,
  settingscommunitydeleted = 0,
  settingscommunitydeletedrestore = 0,

  settingscountry = 488,
  settingscountrymanage = 488,
  settingscountrymanageadd = 2708,
  settingscountrymanageedit = 2709,
  settingscountrymanagedelete = 2710,
  settingscountrydeleted = 0,
  settingscountrydeletedrestore = 0,

  settingsentitytypes = 505,
  settingsentitytypesmanage = 505,
  settingsentitytypesmanageadd = 2769,
  settingsentitytypesmanageedit = 2770,
  settingsentitytypesmanagedelete = 2771,
  settingsentitytypesdeleted = 0,
  settingsentitytypesdeletedrestore = 0,

  settingsexpertise = 550,
  settingsexpertisemanage = 550,
  settingsexpertisemanageadd = 0,
  settingsexpertisemanageedit = 0,
  settingsexpertisemanagedelete = 0,
  settingsexpertisedeleted = 0,
  settingsexpertisedeletedrestore = 0,

  settingslanguagemanage = 0,
  settingslanguagemanageadd = 0,
  settingslanguagemanageedit = 0,
  settingslanguagemanagedelete = 0,
  settingslanguagedeleted = 0,
  settingslanguagedeletedrestore = 0,

  settingsunitvariation = 561,
  settingsunitvariationadd = 3160,
  settingsunitvariationimport = 3159,
  settingsunitvariationimportimport = 3164,
  settingsunitvariationimportmanage = 3161,
  settingsunitvariationimportmanageedit = 3162,
  settingsunitvariationimportmanagedelete = 3163,
  settingsunitvariationimportmanageadd = 3160,
  settingsunitvariationimportmanageimport = 3159,
}

export enum PermissionsForSettings {
  settingsdocumentcategories = 'settingsdocumentcategories',
  settingsfacilities = 'settingsfacilities',
  settingsameinities = 'settingsameinities',
  settingsxml = 'settingsxml',
  settingswebportal = 'settingswebportal',
  settingstax = 'settingstax',
  settingsplatformcredientials = 'settingsplatformcredientials',
  settingsaqaryguidesmanage = 'settingsaqaryguidesmanage',
  settingsaqaryguidesdeleted = 'settingsaqaryguidesdeleted',
  settingsbanksmanage = 'settingsbanksmanage',
  settingsbanksdeleted = 'settingsbanksdeleted',
  settingsbanksmanagesubcategorymanage = 'settingsbanksmanagesubcategorymanage',
  settingsbanksmanagesubcategorydeleted = 'settingsbanksmanagesubcategorydeleted',
  settingsbannercostmanage = 'settingsbannercostmanage',
  settingsbannercostdeleted = 'settingsbannercostdeleted',
  settingsbannerplanpackagedeleted = 'settingsbannerplanpackagedeleted',
  settingsbannerplanpackagemanage = 'settingsbannerplanpackagemanage',
  settingscategory = 'settingscategory',
  settingscitymanage = 'settingscitymanage',
  settingscitydeleted = 'settingscitydeleted',
  settingscompanyactivitiesmanage = 'settingscompanyactivitiesmanage',
  settingscompanyactivitiesdeleted = 'settingscompanyactivitiesdeleted',
  settingscompanycategorymanage = 'settingscompanycategorymanage',
  settingscompanycategorydeleted = 'settingscompanycategorydeleted',
  settingscompanytype = 'settingscompanytype',
  settingscommunitymanage = 'settingscommunitymanage',
  settingscommunitydeleted = 'settingscommunitydeleted',
  settingscountrymanage = 'settingscountrymanage',
  settingscountrydeleted = 'settingscountrydeleted',
  settingsentitytypesmanage = 'settingsentitytypesmanage',
  settingsentitytypesdeleted = 'settingsentitytypesdeleted',
  settingsexpertisemanage = 'settingsexpertisemanage',
  settingsexpertisedeleted = 'settingsexpertisedeleted',
  settingsunitvariationimport = 'settingsunitvariationimport',
  settingsunitvariationimportmanage = 'settingsunitvariationimportmanage',
  settingslanguagemanage = 'settingslanguagemanage',
  settingslanguagedeleted = 'settingslanguagedeleted',
}
