// ! Backend say it will be same forever, but i know it will change in the future.
// ! order is very important for debugging

export enum PagesIdCompanies {
  companies = 5,

  companiesadd = 336,

  companieshistory = 341,

  companiesdeleted = 340,
  companiesdeletedrestore = 1462,

  companiesblocked = 339,
  companiesblockedrestore = 1461,

  companiesinternational = 338,
  companiesinternationalreset = 1460,
  companiesinternationalblock = 1459,
  companiesinternationalview = 1451,
  companiesinternationaledit = 1452,
  companiesinternationallive = 1458,
  companiesinternationaldelete = 0,
  companiesinternationalsubscriptions = 1456,
  companiesinternationalsubscriptionsmakepayment = 2096,
  companiesinternationalleadership = 1453,
  companiesinternationalleadershipdelete = 2083,
  companiesinternationalleadershipadd = 2082,
  companiesinternationalleadershipedit = 2978,
  companiesinternationaldocuments = 1455,
  companiesinternationaldocumentsview = 2094,
  companiesinternationaldocumentsdownload = 2095,
  companiesinternationaldepartment = 1457,
  companiesinternationaldepartmentedit = 2098,
  companiesinternationaldepartmentadd = 2097,
  companiesinternationaldepartmentdelete = 2099,
  companiesinternationaldepartmentroles = 2100,
  companiesinternationaldepartmentrolesedit = 2583,
  companiesinternationaldepartmentrolespreview = 2582,
  companiesinternationaldepartmentrolesadd = 2581,
  companiesinternationaldepartmentrolesdelete = 2584,
  companiesinternationalsubcompanies = 1454,
  companiesinternationalsubcompaniesreset = 2093,
  companiesinternationalsubcompaniesreport = 2091,
  companiesinternationalsubcompaniesblock = 2092,
  companiesinternationalsubcompanieslive = 2090,
  companiesinternationalsubcompaniesedit = 2086,
  companiesinternationalsubcompaniesview = 2085,
  companiesinternationalsubcompaniesadd = 2084,
  companiesinternationalsubcompaniesleadership = 2087,
  companiesinternationalsubcompaniesleadershipadd = 2570,
  companiesinternationalsubcompaniesleadershipdelete = 2571,
  companiesinternationalsubcompaniessubscriptions = 2089,
  companiesinternationalsubcompaniessubscriptionsmakepayment = 2576,
  companiesinternationalsubcompaniessubscriptionsviewprofile = 2575,
  companiesinternationalsubcompaniessubscriptionsviewcontract = 2574,
  companiesinternationalsubcompaniesdocuments = 2088,
  companiesinternationalsubcompaniesdocumentsview = 2579,
  companiesinternationalsubcompaniesdocumentsdownload = 2580,

  companieslocal = 337,
  companieslocaledit = 1438,
  companieslocallive = 1447,
  companieslocaldelete = 0,
  companieslocalreset = 1450,
  companieslocalblock = 1449,
  companieslocalview = 1437,
  companieslocalleadership = 1439,
  companieslocalleadershipdelete = 2064,
  companieslocalleadershipadd = 2063,
  companieslocalleadershipedit = 2977,
  companieslocaldocuments = 1441,
  companieslocaldocumentsview = 2075,
  companieslocaldocumentsdownload = 2076,
  companieslocalsubscriptions = 1446,
  companieslocalsubscriptionsmakepayment = 2077,
  companieslocaldepartment = 1448,
  companieslocaldepartmentedit = 2079,
  companieslocaldepartmentadd = 2078,
  companieslocaldepartmentdelete = 2080,
  companieslocaldepartmentroles = 2081,
  companieslocaldepartmentrolesadd = 2566,
  companieslocaldepartmentrolesdelete = 2569,
  companieslocaldepartmentrolespreview = 2567,
  companieslocaldepartmentrolesedit = 2568,
  companieslocalsubcompanies = 1440,
  companieslocalsubcompaniesreset = 2074,
  companieslocalsubcompaniesreport = 2072,
  companieslocalsubcompaniesblock = 2073,
  companieslocalsubcompanieslive = 2071,
  companieslocalsubcompaniesedit = 2067,
  companieslocalsubcompaniesview = 2066,
  companieslocalsubcompaniesadd = 2065,
  companieslocalsubcompaniesleadership = 2068,
  companieslocalsubcompaniesleadershipadd = 2559,
  companieslocalsubcompaniesleadershipdelete = 2560,
  companieslocalsubcompaniessubscriptions = 2070,
  companieslocalsubcompaniessubscriptionsmakepayment = 2565,
  companieslocalsubcompaniessubscriptionsviewprofile = 2564,
  companieslocalsubcompaniessubscriptionsviewcontract = 2563,
  companieslocalsubcompaniesdocuments = 2069,
  companieslocalsubcompaniesdocumentsview = 2561,
  companieslocalsubcompaniesdocumentsdownload = 2562,
}

export enum PermissionsForCompanies {
  companiesdeleted = 'companiesdeleted',
  companiesblocked = 'companiesblocked',
  companiesinternational = 'companiesinternational',
  companiesinternationalsubscriptions = 'companiesinternationalsubscriptions',
  companiesinternationalleadership = 'companiesinternationalleadership',
  companiesinternationaldocuments = 'companiesinternationaldocuments',
  companiesinternationaldepartment = 'companiesinternationaldepartment',
  companiesinternationaldepartmentroles = 'companiesinternationaldepartmentroles',
  companiesinternationalsubcompanies = 'companiesinternationalsubcompanies',
  companiesinternationalsubcompaniesleadership = 'companiesinternationalsubcompaniesleadership',
  companiesinternationalsubcompaniessubscriptions = 'companiesinternationalsubcompaniessubscriptions',
  companiesinternationalsubcompaniesdocuments = 'companiesinternationalsubcompaniesdocuments',
  companieslocal = 'companieslocal',
  companieslocalsubscriptions = 'companieslocalsubscriptions',
  companieslocalleadership = 'companieslocalleadership',
  companieslocaldocuments = 'companieslocaldocuments',
  companieslocaldepartment = 'companieslocaldepartment',
  companieslocaldepartmentroles = 'companieslocaldepartmentroles',
  companieslocalsubcompanies = 'companieslocalsubcompanies',
  companieslocalsubcompaniesleadership = 'companieslocalsubcompaniesleadership',
  companieslocalsubcompaniessubscriptions = 'companieslocalsubcompaniessubscriptions',
  companieslocalsubcompaniesdocuments = 'companieslocalsubcompaniesdocuments',
}
