// ! Backend say it will be same forever, but i know it will change in the future.
// ! order is very important for debugging

export enum PagesIdAgriculture {
  agriculture = 9,
  agriculturehistory = 370,
  agricultureadd = 363,

  agriculturedeleted = 369,
  agriculturedeletedrestore = 1577,
  agriculturedeletedrestoredocuments = 0,

  agriculturemanagerequests = 0,
  agriculturemanagerequestsmanage = 0,

  agricultureblocked = 0,
  agricultureblockedunblock = 0,

  agriculturepublished = 322,
  agriculturepublishedunshare = 1385,
  agriculturepublishedsocialmedia = 1387,
  agriculturepublishedunpublish = 1386,
  agriculturepublishedwebportals = 1388,
  agriculturepublishedview = 1384,

  agricultureshared = 319,
  agriculturesharedinternationalshare = 1381,
  agriculturesharedunshare = 1377,
  agriculturesharedlocalshare = 1380,
  agriculturesharedview = 1376,
  agriculturesharedinternalshare = 1379,
  agriculturesharedunpublish = 1378,

  agriculturesharedwithme = 323,
  agriculturesharedwithmeduplicate = 1389,
  agriculturesharedwithmegallery = 1392,
  agriculturesharedwithmegalleryadd = 2029,
  agriculturesharedwithmegallerydelete = 2030,

  agricultureinternationalproperties = 318,
  agricultureinternationalpropertiesshare = 1367,
  agricultureinternationalpropertiespublish = 1368,
  agricultureinternationalpropertiesedit = 1366,
  agricultureinternationalpropertiesdelete = 1369,
  agricultureinternationalpropertiesview = 1365,
  agricultureinternationalpropertiesadd = 1364,
  agricultureinternationalpropertiesdocuments = 1375,
  agricultureinternationalpropertiesdocumentsview = 2026,
  agricultureinternationalpropertiesdocumentsadd = 0,
  agricultureinternationalpropertiesdocumentsdelete = 2028,
  agricultureinternationalpropertiesdocumentsdownload = 2027,
  agricultureinternationalpropertiesunittype = 1371,
  agricultureinternationalpropertiesunittypedelete = 2009,
  agricultureinternationalpropertiesunittypeedit = 2008,
  agricultureinternationalpropertiesunittypeview = 2007,
  agricultureinternationalpropertiesunittypeadd = 2006,
  agricultureinternationalpropertiesplans = 1370,
  agricultureinternationalpropertiesplansdelete = 2005,
  agricultureinternationalpropertiesplansview = 2003,
  agricultureinternationalpropertiesplansedit = 2004,
  agricultureinternationalpropertiesplansadd = 2002,
  agricultureinternationalpropertiespayment = 1373,
  agricultureinternationalpropertiespaymentedit = 2021,
  agricultureinternationalpropertiespaymentdelete = 2022,
  agricultureinternationalpropertiespaymentadd = 2020,
  agricultureinternationalpropertiesgallery = 1374,
  agricultureinternationalpropertiesgalleryadd = 2023,
  agricultureinternationalpropertiesgalleryedit = 2024,
  agricultureinternationalpropertiesgallerydelete = 2025,
  agricultureinternationalpropertiesunits = 1372,
  agricultureinternationalpropertiesunitsadd = 2010,
  agricultureinternationalpropertiesunitsview = 2011,
  agricultureinternationalpropertiesunitsedit = 2012,
  agricultureinternationalpropertiesunitsdelete = 2015,
  agricultureinternationalpropertiesunitscopy = 2016,
  agricultureinternationalpropertiesunitsshare = 2013,
  agricultureinternationalpropertiesunitspublish = 2014,
  agricultureinternationalpropertiesunitsplans = 2017,
  agricultureinternationalpropertiesunitsplansadd = 2546,
  agricultureinternationalpropertiesunitsplansdelete = 2549,
  agricultureinternationalpropertiesunitsplansview = 2547,
  agricultureinternationalpropertiesunitsplansedit = 2548,
  agricultureinternationalpropertiesunitsgallery = 2019,
  agricultureinternationalpropertiesunitsgalleryadd = 2555,
  agricultureinternationalpropertiesunitsgalleryimport = 2556,
  agricultureinternationalpropertiesunitsgallerydelete = 2558,
  agricultureinternationalpropertiesunitsgalleryedit = 2557,
  agricultureinternationalpropertiesunitsdocuments = 2018,
  agricultureinternationalpropertiesunitsdocumentsadd = 2550,
  agricultureinternationalpropertiesunitsdocumentsdelete = 2554,
  agricultureinternationalpropertiesunitsdocumentsdownload = 2553,
  agricultureinternationalpropertiesunitsdocumentsview = 2552,
  agricultureinternationalpropertiesunitsdocumentsimport = 2551,

  agriculturelocalproperties = 317,
  agriculturelocalpropertiesshare = 1355,
  agriculturelocalpropertiesadd = 1352,
  agriculturelocalpropertiesedit = 1354,
  agriculturelocalpropertiespublish = 1356,
  agriculturelocalpropertiesview = 1353,
  agriculturelocalpropertiesdelete = 1357,
  agriculturelocalpropertiespayment = 1361,
  agriculturelocalpropertiespaymentedit = 1994,
  agriculturelocalpropertiespaymentdelete = 1995,
  agriculturelocalpropertiespaymentadd = 1993,
  agriculturelocalpropertiesdocuments = 1363,
  agriculturelocalpropertiesdocumentsview = 1999,
  agriculturelocalpropertiesdocumentsadd = 0,
  agriculturelocalpropertiesdocumentsdownload = 2000,
  agriculturelocalpropertiesdocumentsdelete = 2001,
  agriculturelocalpropertiesgallery = 1362,
  agriculturelocalpropertiesgallerydelete = 1998,
  agriculturelocalpropertiesgalleryadd = 1996,
  agriculturelocalpropertiesgalleryedit = 1997,
  agriculturelocalpropertiesplans = 1358,
  agriculturelocalpropertiesplansadd = 1975,
  agriculturelocalpropertiesplansdelete = 1978,
  agriculturelocalpropertiesplansedit = 1977,
  agriculturelocalpropertiesplansview = 1976,
}

export enum PermissionsForAgriculture {
  agriculturedeleted = 'agriculturedeleted',
  agriculturemanagerequests = 'agriculturemanagerequests',
  agricultureblocked = 'agricultureblocked',
  agriculturepublished = 'agriculturepublished',
  agricultureshared = 'agricultureshared',
  agriculturesharedwithme = 'agriculturesharedwithme',
  agriculturesharedwithmegallery = 'agriculturesharedwithmegallery',
  agricultureinternationalproperties = 'agricultureinternationalproperties',
  agricultureinternationalpropertiesdocuments = 'agricultureinternationalpropertiesdocuments',
  agricultureinternationalpropertiesunittype = 'agricultureinternationalpropertiesunittype',
  agricultureinternationalpropertiesplans = 'agricultureinternationalpropertiesplans',
  agricultureinternationalpropertiespayment = 'agricultureinternationalpropertiespayment',
  agricultureinternationalpropertiesgallery = 'agricultureinternationalpropertiesgallery',
  agriculturelocalproperties = 'agriculturelocalproperties',
  agriculturelocalpropertiesdocuments = 'agriculturelocalpropertiesdocuments',
  agriculturelocalpropertiesplans = 'agriculturelocalpropertiesplans',
  agriculturelocalpropertiespayment = 'agriculturelocalpropertiespayment',
  agriculturelocalpropertiesgallery = 'agriculturelocalpropertiesgallery',
}
