// ! Backend say it will be same forever, but i know it will change in the future.
// ! order is very important for debugging

export enum PagesIdUnits {
  units = 4,

  unitsdeleted = 334,
  unitsdeletedrestore = 1436,

  unitsadd = 327,

  unitsrejected = 333,
  unitsrejectedaccept = 1435,

  unitspublished = 331,
  unitspublishedunpublish = 1430,
  unitspublishedsocialmedia = 1431,
  unitspublishedwebportals = 1432,
  unitspublishedunshare = 1429,
  unitspublishedview = 1428,

  unitssharedwithme = 332,
  unitssharedwithmeduplicate = 1433,
  unitssharedwithmegallery = 1434,
  unitssharedwithmegallerydelete = 2062,
  unitssharedwithmegalleryimport = 2061,
  unitssharedwithmegalleryadd = 2060,

  unitslocal = 328,
  unitslocaldelete = 1400,
  unitslocaladd = 1395,
  unitslocaledit = 1397,
  unitslocallive = 1401,
  unitslocalview = 1396,
  unitslocalpublish = 1399,
  unitslocalexclusive = 1407,
  unitslocalshare = 1398,
  unitslocalpayment = 1404,
  unitslocalpaymentadd = 2035,
  unitslocalpaymentedit = 2036,
  unitslocalpaymentdelete = 2037,
  unitslocalplans = 1402,
  unitslocalplansdownload = 2033,
  unitslocalplansdelete = 2034,
  unitslocalplansedit = 2032,
  unitslocalplansadd = 2031,
  unitslocalgallery = 1405,
  unitslocalgalleryedit = 2039,
  unitslocalgalleryadd = 2038,
  unitslocalgallerydelete = 2040,
  unitslocaldocuments = 1406,
  unitslocaldocumentsdownload = 2043,
  unitslocaldocumentsadd = 2041,
  unitslocaldocumentsview = 2042,
  unitslocaldocumentsdelete = 2044,

  unitsinternational = 329,
  unitsinternationaladd = 1408,
  unitsinternationalshare = 1411,
  unitsinternationalview = 1409,
  unitsinternationaldelete = 1413,
  unitsinternationallive = 1414,
  unitsinternationaledit = 1410,
  unitsinternationalexclusive = 1420,
  unitsinternationalpublish = 1412,
  unitsinternationalpayment = 1416,
  unitsinternationalpaymentadd = 2049,
  unitsinternationalpaymentedit = 2050,
  unitsinternationalpaymentdelete = 2051,
  unitsinternationalplans = 1415,
  unitsinternationalplansdownload = 2047,
  unitsinternationalplansdelete = 2048,
  unitsinternationalplansedit = 2046,
  unitsinternationalplansadd = 2045,
  unitsinternationaldocuments = 1419,
  unitsinternationaldocumentsdownload = 2057,
  unitsinternationaldocumentsadd = 2055,
  unitsinternationaldocumentsview = 2056,
  unitsinternationaldocumentsdelete = 2058,
  unitsinternationalgallery = 1417,
  unitsinternationalgalleryedit = 2053,
  unitsinternationalgalleryadd = 2052,
  unitsinternationalgallerydelete = 2054,

  unitsshared = 330,
  unitssharedunpublish = 1423,
  unitssharedview = 1421,
  unitssharedunshare = 1422,
  unitssharedinternalshare = 1424,
  unitssharedlocalshare = 1425,
  unitssharedinternationalshare = 1427,
  unitssharedinternationalshareview = 2059,
}

export enum PermissionsForUnits {
  unitsdeleted = 'unitsdeleted',
  unitsrejected = 'unitsrejected',
  unitspublished = 'unitspublished',
  unitssharedwithme = 'unitssharedwithme',
  unitssharedwithmegallery = 'unitssharedwithmegallery',
  unitslocal = 'unitslocal',
  unitslocalpayment = 'unitslocalpayment',
  unitslocalplans = 'unitslocalplans',
  unitslocalgallery = 'unitslocalgallery',
  unitslocaldocuments = 'unitslocaldocuments',
  unitsinternational = 'unitsinternational',
  unitsinternationalpayment = 'unitsinternationalpayment',
  unitsinternationalplans = 'unitsinternationalplans',
  unitsinternationaldocuments = 'unitsinternationaldocuments',
  unitsinternationalgallery = 'unitsinternationalgallery',
  unitsshared = 'unitsshared',
}
